{
  name: "Brandenburg Concertos",
  year: 1989,
  by: [
    {
      name: "Johann Sebastian Bach"
    },
    {
      name: "Orchestra of the Age of Enlightenment"
    }
  ],
  mediums: [
    {
      number: 1,
      songs: [
        {
          track: 1,
          name: "Brandenburg Concerto No. 1 in F: I. Allegro",
          duration: (PT4M5S)
        },
        {
          track: 2,
          name: "Brandenburg Concerto No. 1 in F: II. Adagio",
          duration: (PT3M44S)
        },
        {
          track: 3,
          name: "Brandenburg Concerto No. 1 in F: III. Allegro",
          duration: (PT4M14S)
        },
        {
          track: 4,
          name: "Brandenburg Concerto No. 1 in F: IV. Menuet",
          duration: (PT7M36S)
        }
      ]
    }
  ]
}